### ISSUE TITLE
Skin slows down with time

### ISSUE THREAD

**Issue by nils-werner** [jurialmunkey/skin.eminence#34]
I am using this skin on my OpenELEC Raspi media center and have noticed its framerate of the menus (not video) dropping over the course of an hour or two. I suspect it might be some sort of memory or "another kind of" leak.

**Comment by jurialmunkey** [comment]
Debug Logs?

**Comment by phedlund** [comment]
I actually updated to openELEC 5.0 final and then deleted all files in .kodi related to eminence. Then I did a new install of eminence (github master) and the problem is now gone.
