### ISSUE TITLE
Show "unwatched episodes" count on library

### ISSUE THREAD

**Issue by hackedbellini** [jurialmunkey/skin.eminence#37]
One thing that prevented me from migrating from amber to this was: On amber, I can easily see how many unwatched episode a tv show has, facilitating my decision on "what to watch tonight?"

I think it would be great to have the same functionality here (even if it was only available if an option is turned on). So, instead of presenting a true/false marker for "the tv show is (un)watched", you could show the number of unwatched episodes. For example, this is how this is handled now:

```
  Tv show A  (*)
  Tv show B  ( )
  Tv show C  ( )
  Tv show D  (*)
```

And that's my idea:

```
  Tv show A  (*)
  Tv show B  (1)
  Tv show C  (37)
  Tv show D  (*)
```

What do you think?

**Comment by jurialmunkey** [comment]
A simple solution is to open the side pane menu on the right and click "Hide Watched". Every view except wall will show the number of unwatched episodes when sorted by title when hide watched is enabled.
