### ISSUE TITLE
Problem with weather Function

### ISSUE THREAD

**Issue by ffantazzini** [jurialmunkey/skin.eminence#44]
Today I updated my Openhour Chameleon (previously firmware was 1.0.10 with SPMC 13.4) to resolve a problem on HDCP Handshaking that was fixed by the new beta firmware 1.0.11.
So I upgraded the firmware and SPMC too (now 14.1 beta 1).
Finally I installed Eminence Skin (the best skin, in my opinion), release 1.2.2: everything works quite fine.
Just two things to list:
- some labels are not translated if i choose a different language from english (they still remain in english)
- if i choose the weather function appears a black screen. The yahoo weather add-on is configured correctly because if i switch on confluence skin, the weather function is ok and i can see all the informations and the icons.
@jurialmunkey, I hope these informations could help your great job.

**Comment by jurialmunkey** [comment]
Weather is now fixed, there was a small typo in the file that I accidentally uploaded. For translations, you can assist by creating a transifex account and helping out at: 
https://www.transifex.com/projects/p/xbmc-skins/resource/skin-eminence/

Also, some translations can take a little while to make it into the skin.
