### ISSUE TITLE
Home tiles limit

### ISSUE THREAD

**Issue by agn4965** [jurialmunkey/skin.eminence#47]
Should there be a limit to how many tiles I can add to the home menu?
Whenever I try to insert a new one now it will just take the place of an existing tile.

**Comment by jurialmunkey** [comment]
Yeah there is a limit. Can't remember exactly, but from memory I think it is 22 (excluding settings/power).

**Comment by agn4965** [comment]
Can I remove the limit?

**Comment by agn4965** [comment]
Please respond

**Comment by jurialmunkey** [comment]
No, not without recoding the skin.
